// export const FETCH_JOBS = 'FETCH_JOBS';
export const FETCH_JOBS_SUCCEEDED = 'FETCH_JOBS_SUCCEEDED';
export const FETCH_JOBS_FAILED = 'FETCH_JOBS_FAILED';
export const FETCH_DETAILS_SUCCEEDED = 'FETCH_JOBS_SUCCEEDED';
export const FETCH_DETAILS_FAILED = 'FETCH_JOBS_FAILED';
export const CHANGE_FILTER = 'CHANGE_FILTER';
